# Generated by Django 6.1 on 2026-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='properties/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listing_type', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling'), ('renting', 'Renting')], max_length=10)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='For Sale', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this listing from the public site without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
