# Generated by Django 6.1 on 2026-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinaRealty', '0002_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(blank=True, choices=[('buying', 'Buying'), ('selling', 'Selling'), ('renting', 'Renting'), ('other', 'Something else')], max_length=10)),
                ('agent', models.CharField(blank=True, help_text='Preferred agent, if any', max_length=120)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
