# Generated by Django 6.1 on 2026-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinaRealty', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(help_text='e.g. Lodha Group', max_length=120)),
                ('project_name', models.CharField(help_text='e.g. Lodha Malad Heights', max_length=200)),
                ('location', models.CharField(help_text='e.g. Malad West, Mumbai', max_length=255)),
                ('configuration', models.CharField(blank=True, help_text='e.g. 2 & 3 BHK', max_length=120)),
                ('starting_price', models.CharField(blank=True, help_text='e.g. ₹1.25 Cr onwards', max_length=80)),
                ('highlight', models.CharField(blank=True, help_text='e.g. Most Selling in Malad', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Large project/building photo. Optional — a styled gradient shows if left empty.', upload_to='promos/')),
                ('link_url', models.URLField(blank=True, help_text="Where the 'View Project' button goes. Leave blank to link to the properties page.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this promo from the public site without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Project promos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
