# Generated by Django 6.1 on 2026-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinaRealty', '0005_seed_project_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpromo',
            name='highlights',
            field=models.TextField(blank=True, help_text='2-4 short project highlights to show on the card — one per line.'),
        ),
        migrations.AlterField(
            model_name='projectpromo',
            name='highlight',
            field=models.CharField(blank=True, help_text="e.g. Most Selling in Malad (shown as the card's badge)", max_length=120),
        ),
        migrations.AlterField(
            model_name='projectpromo',
            name='image',
            field=models.ImageField(blank=True, help_text='Large project/building photo. Optional — a styled placeholder shows if left empty.', upload_to='promos/'),
        ),
        migrations.AlterField(
            model_name='projectpromo',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this promotional card from the public site without deleting it.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='projectpromo',
            name='link_url',
            field=models.URLField(blank=True, help_text="Where the 'View Project' button goes. Leave blank to scroll to the property listings."),
        ),
    ]
